name: Biome CI

on: [push, pull_request]

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v5
      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci
